export const PRESET_SIZES = [
  { label: '6 × 12"', width: 6, height: 12 },
  { label: '12 × 12"', width: 12, height: 12 },
  { label: '12 × 18"', width: 12, height: 18 },
  { label: '12 × 24"', width: 12, height: 24 },
  { label: '18 × 24"', width: 18, height: 24 },
  { label: '18 × 32"', width: 18, height: 32 },
  { label: '24 × 24"', width: 24, height: 24 },
  { label: '24 × 36"', width: 24, height: 36 },
  { label: '24 × 48"', width: 24, height: 48 },
  { label: 'Custom', width: null, height: null },
];

export const PPI = 96;

export const PATTERN_TYPES = [
  { id: 'spirograph', label: 'Spirograph' },
  { id: 'flowfield', label: 'Flow Field' },
  { id: 'phyllotaxis', label: 'Phyllotaxis' },
  { id: 'wave', label: 'Waves' },
  { id: 'voronoi', label: 'Voronoi' },
  { id: 'recursive', label: 'Recursive' },
  { id: 'phyllodash', label: 'Phyllotaxis Dash' },
  { id: 'grainfield', label: 'Grain Field' },
  { id: 'flowhatch', label: 'Flow Hatch' },
  { id: 'feather', label: 'Feather' },
  { id: 'turing', label: 'Turing' },
  { id: 'duality', label: 'Duality' },
  { id: 'radialetch', label: 'Radial Etch' },
  { id: 'grid', label: 'Grid' },
  { id: 'spiral', label: 'Spiral' },
];

export const MAX_LAYERS = 6;

export const DEFAULT_PARAMS = {
  spirograph: {
    R: 200,
    r: 75,
    d: 100,
    revolutions: 20,
    strokeWeight: 1,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  flowfield: {
    particleCount: 800,
    stepLength: 5,
    noiseScale: 0.004,
    curlStrength: 90,
    patternScale: 1,
    strokeWeight: 1,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  phyllotaxis: {
    count: 500,
    angle: 137.508,
    spacing: 6,
    minSize: 2,
    maxSize: 16,
    sizeGrowth: 0.5,
    shape: 'circle',
    fillMode: 'outline',
    rotation: 0,
    strokeWeight: 1,
    jitter: 0,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  wave: {
    waveCount: 5,
    frequency: 6,
    amplitude: 45,
    lineSpacing: 12,
    strokeWeight: 1,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  voronoi: {
    cellCount: 80,
    jitter: 40,
    drawMode: 'outlines',
    relaxationSteps: 2,
    strokeWeight: 1,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  recursive: {
    shape: 'hexagon',
    depth: 5,
    startScale: 70,
    rotationPerLevel: 15,
    scaleFactor: 0.7,
    scaleNonLinearity: 0,
    strokeWeight: 1,
    strokeDepthDecay: 0,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  phyllodash: {
    seedCount: 2000,
    spacingC: 9,
    innerMax: 8,
    outerMax: 18,
    noiseScale: 0.008,
    strokeWeight: 1,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  grainfield: {
    pointCount: 150,
    relaxPasses: 4,
    neighborK: 3,
    minDashLen: 6,
    maxDashLen: 28,
    strokeWeight: 1,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  flowhatch: {
    particleCount: 200,
    stepsPerParticle: 80,
    stepLength: 5,
    sampleEvery: 3,
    noiseScale: 0.005,
    minDashLen: 8,
    maxDashLen: 24,
    strokeWeight: 1,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  feather: {
    curveType: 'hypotrochoid',
    R: 180,
    r: 60,
    d: 80,
    roseK: 5,
    roseA: 200,
    sampleCount: 1200,
    harmonicK: 6,
    innerBase: 2,
    innerAmp: 10,
    outerBase: 2,
    outerAmp: 14,
    strokeWeight: 1,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  turing: {
    preset: 'spots',
    simIterations: 80,
    gridRes: 150,
    targetPoints: 600,
    minSpacing: 8,
    minDashLen: 4,
    maxDashLen: 20,
    strokeWeight: 1,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  duality: {
    // Spiral + dashes
    innerRadius: 15, outerRadius: 450,
    spiralTurns: 8, spiralGrowth: 1.0,
    dashCount: 400, dashLength: 18, dashLenJitter: 0.4,
    dashSparsity: 0.12, angleJitter: 0.2,
    dashStrokeWeight: 1.2,
    // Arcs
    arcCount: 14, arcSpacingNL: 1.8, arcRadiusJitter: 3,
    arcMinAngle: 40, arcMaxAngle: 260, arcMaxLength: 700,
    arcAngleJitter: 1.0, arcStrokeWeight: 0.8,
    // Intersection
    overlapGap: 5, overlapPriority: 0.0,
    originX: 0.5, originY: 0.5, symmetry: 1, startAngle: 0,
  },
  radialetch: {
    lineCount: 120,
    innerRadius: 20,
    outerRadius: 400,
    lengthJitter: 0.3,
    angleJitter: 0,
    noiseWarp: 0,
    noiseScale: 0.005,
    strokeWeight: 1,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  grid: {
    cols: 12,
    rows: 12,
    spacing: 40,
    nonLinear: 0,
    jitter: 0,
    drawHorizontal: 1,
    drawVertical: 1,
    margin: 20,
    strokeWeight: 1,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
  spiral: {
    armCount: 3,
    turns: 8,
    innerRadius: 5,
    outerRadius: 400,
    growth: 1.0,
    distortAmount: 0,
    distortScale: 0.01,
    wobbleAmp: 0,
    wobbleFreq: 8,
    stepsPerTurn: 120,
    strokeWeight: 1,
    symmetry: 1,
    startAngle: 0,
    offsetX: 0,
    offsetY: 0,
  },
};

const SYMMETRY_PARAM = { key: 'symmetry', label: 'Radial Symmetry', min: 1, max: 11, step: 1, tooltip: 'Number of radial copies — 1 = none, 2 = mirror, 3 = 120°, etc.' };
const START_ANGLE_PARAM = { key: 'startAngle', label: 'Start Angle', min: 0, max: 360, step: 1, tooltip: 'Rotates the entire pattern by this many degrees' };
const OFFSET_X_PARAM = { key: 'offsetX', label: 'Offset X', min: -500, max: 500, step: 1, tooltip: 'Shifts the pattern horizontally in pixels' };
const OFFSET_Y_PARAM = { key: 'offsetY', label: 'Offset Y', min: -500, max: 500, step: 1, tooltip: 'Shifts the pattern vertically in pixels' };

export const PATTERN_PARAM_DEFS = {
  spirograph: [
    { key: 'R', label: 'Outer Radius', min: 50, max: 1200, step: 1, tooltip: 'Radius of the outer fixed circle — can exceed frame for edge-to-edge coverage' },
    { key: 'r', label: 'Inner Radius', min: 10, max: 600, step: 1, tooltip: 'Radius of the rolling inner circle' },
    { key: 'd', label: 'Pen Offset', min: 10, max: 600, step: 1, tooltip: 'Distance from center of inner circle to pen point' },
    { key: 'revolutions', label: 'Revolutions', min: 1, max: 40, step: 1, tooltip: 'Number of full rotations to draw' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 3, step: 0.1, tooltip: 'Line thickness' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  flowfield: [
    { key: 'particleCount', label: 'Particle Count', min: 100, max: 3000, step: 10, tooltip: 'Number of particles tracing the flow field' },
    { key: 'stepLength', label: 'Step Length', min: 1, max: 20, step: 1, tooltip: 'Distance each particle moves per step' },
    { key: 'noiseScale', label: 'Noise Scale', min: 0.001, max: 0.02, step: 0.001, tooltip: 'Scale of Perlin noise — smaller = smoother' },
    { key: 'curlStrength', label: 'Curl Strength', min: 1, max: 360, step: 1, tooltip: 'Angle multiplier for noise-based direction' },
    { key: 'patternScale', label: 'Pattern Scale', min: 1, max: 2, step: 0.05, tooltip: 'Expands the generation area — increase to hide edges when using symmetry' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 4, step: 0.1, tooltip: 'Line thickness' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  phyllotaxis: [
    { key: 'count', label: 'Count', min: 10, max: 5000, step: 10, tooltip: 'Number of elements — higher values fill more of the frame' },
    { key: 'angle', label: 'Divergence Angle', min: 100, max: 170, step: 0.01, tooltip: 'Angle between elements — 137.508° is the golden angle' },
    { key: 'spacing', label: 'Spacing', min: 0.5, max: 30, step: 0.5, tooltip: 'Radial spacing — larger values spread the spiral beyond the frame edges' },
    { key: 'minSize', label: 'Min Size', min: 0.5, max: 40, step: 0.5, tooltip: 'Size of innermost elements' },
    { key: 'maxSize', label: 'Max Size', min: 1, max: 120, step: 0.5, tooltip: 'Size of outermost elements' },
    { key: 'sizeGrowth', label: 'Size Growth', min: 0, max: 3, step: 0.05, tooltip: 'How size scales from center to edge — 0 = uniform, 1 = linear, >1 = accelerating' },
    { key: 'shape', label: 'Shape', type: 'select', options: [
      { value: 'circle', label: 'Circle' },
      { value: 'square', label: 'Square' },
      { value: 'triangle', label: 'Triangle' },
      { value: 'hexagon', label: 'Hexagon' },
      { value: 'star', label: 'Star' },
    ], tooltip: 'Shape of each element' },
    { key: 'fillMode', label: 'Fill Mode', type: 'select', options: [
      { value: 'outline', label: 'Outline (cut)' },
      { value: 'fill', label: 'Fill (engrave)' },
      { value: 'both', label: 'Fill + Outline' },
    ], tooltip: 'Outline for laser cut, fill for engraving' },
    { key: 'rotation', label: 'Element Rotation', min: 0, max: 360, step: 1, tooltip: 'Base rotation of each element in degrees' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 4, step: 0.1, tooltip: 'Outline thickness' },
    { key: 'jitter', label: 'Jitter', min: 0, max: 100, step: 1, tooltip: 'Random displacement of each element' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  wave: [
    { key: 'waveCount', label: 'Wave Count', min: 2, max: 12, step: 1, tooltip: 'Number of overlapping wave layers' },
    { key: 'frequency', label: 'Frequency', min: 1, max: 20, step: 0.5, tooltip: 'Number of wave cycles across the canvas' },
    { key: 'amplitude', label: 'Amplitude', min: 5, max: 500, step: 1, tooltip: 'Maximum wave height in pixels — can exceed frame for edge bleed' },
    { key: 'lineSpacing', label: 'Line Spacing', min: 4, max: 40, step: 1, tooltip: 'Vertical space between wave lines' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 3, step: 0.1, tooltip: 'Line thickness' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  voronoi: [
    { key: 'cellCount', label: 'Cell Count', min: 10, max: 800, step: 1, tooltip: 'Number of Voronoi seed points' },
    { key: 'jitter', label: 'Jitter', min: 0, max: 100, step: 1, tooltip: 'Randomness of seed point placement' },
    { key: 'drawMode', label: 'Draw Mode', type: 'select', options: [
      { value: 'outlines', label: 'Cell Outlines' },
      { value: 'delaunay', label: 'Delaunay Triangles' },
      { value: 'both', label: 'Both' },
      { value: 'spokes', label: 'Centroids + Spokes' },
    ], tooltip: 'How to render the Voronoi diagram' },
    { key: 'relaxationSteps', label: 'Relaxation Steps', min: 0, max: 5, step: 1, tooltip: "Lloyd's relaxation passes for more even cells" },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 3, step: 0.1, tooltip: 'Line thickness' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  recursive: [
    { key: 'shape', label: 'Shape', type: 'select', options: [
      { value: 'square', label: 'Square' },
      { value: 'triangle', label: 'Triangle' },
      { value: 'pentagon', label: 'Pentagon' },
      { value: 'hexagon', label: 'Hexagon' },
      { value: 'circle', label: 'Circle (72-gon)' },
    ], tooltip: 'Base shape for recursive subdivision' },
    { key: 'depth', label: 'Depth', min: 1, max: 12, step: 1, tooltip: 'Recursion depth — more = more nested shapes' },
    { key: 'startScale', label: 'Start Size %', min: 20, max: 200, step: 5, tooltip: 'Starting radius as % of half-canvas — over 100% extends beyond the frame edges' },
    { key: 'rotationPerLevel', label: 'Rotation/Level', min: 0, max: 90, step: 1, tooltip: 'Rotation applied at each recursion level' },
    { key: 'scaleFactor', label: 'Scale Factor', min: 0.3, max: 0.95, step: 0.01, tooltip: 'Size multiplier per recursion level' },
    { key: 'scaleNonLinearity', label: 'Scale Non-Linearity', min: -1, max: 1, step: 0.05, tooltip: 'Curves the scale decay — negative = slower start/faster end, positive = faster start/slower end' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 3, step: 0.1, tooltip: 'Base line thickness at level 0' },
    { key: 'strokeDepthDecay', label: 'Stroke Depth Decay', min: 0, max: 1, step: 0.05, tooltip: 'How much stroke thins per recursion level — 0 = uniform, 1 = max thinning' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  phyllodash: [
    { key: 'seedCount', label: 'Seed Count', min: 200, max: 8000, step: 50, tooltip: 'Number of anchor points in the phyllotaxis spiral' },
    { key: 'spacingC', label: 'Spacing', min: 4, max: 20, step: 0.5, tooltip: 'Spacing constant — controls how dense the spiral is' },
    { key: 'innerMax', label: 'Inner Extent', min: 0, max: 30, step: 1, tooltip: 'Max inward dash extent from anchor (pixels)' },
    { key: 'outerMax', label: 'Outer Extent', min: 2, max: 50, step: 1, tooltip: 'Max outward dash extent from anchor (pixels)' },
    { key: 'noiseScale', label: 'Noise Scale', min: 0.002, max: 0.03, step: 0.001, tooltip: 'Perlin noise frequency for dash modulation' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 3, step: 0.1, tooltip: 'Line thickness' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  grainfield: [
    { key: 'pointCount', label: 'Point Count', min: 40, max: 600, step: 10, tooltip: 'Number of seed points for CVT relaxation' },
    { key: 'relaxPasses', label: 'Relaxation Passes', min: 0, max: 8, step: 1, tooltip: '0 = random, higher = more uniform spacing' },
    { key: 'neighborK', label: 'Neighbor Count', min: 2, max: 6, step: 1, tooltip: 'Number of neighbors for grain angle averaging' },
    { key: 'minDashLen', label: 'Min Dash Length', min: 2, max: 30, step: 1, tooltip: 'Shortest dashes (dense regions)' },
    { key: 'maxDashLen', label: 'Max Dash Length', min: 10, max: 80, step: 1, tooltip: 'Longest dashes (sparse regions)' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 3, step: 0.1, tooltip: 'Line thickness' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  flowhatch: [
    { key: 'particleCount', label: 'Particle Count', min: 50, max: 1000, step: 10, tooltip: 'Number of particles walking the flow field' },
    { key: 'stepsPerParticle', label: 'Steps/Particle', min: 20, max: 300, step: 10, tooltip: 'How far each particle walks' },
    { key: 'stepLength', label: 'Step Length', min: 2, max: 15, step: 1, tooltip: 'Pixels per step' },
    { key: 'sampleEvery', label: 'Sample Every N', min: 1, max: 10, step: 1, tooltip: 'Place an anchor every N steps — lower = denser' },
    { key: 'noiseScale', label: 'Noise Scale', min: 0.002, max: 0.02, step: 0.001, tooltip: 'Perlin noise frequency for the flow field' },
    { key: 'minDashLen', label: 'Min Dash Length', min: 4, max: 40, step: 1, tooltip: 'Minimum perpendicular dash length' },
    { key: 'maxDashLen', label: 'Max Dash Length', min: 6, max: 60, step: 1, tooltip: 'Maximum perpendicular dash length' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 3, step: 0.1, tooltip: 'Line thickness' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  feather: [
    { key: 'curveType', label: 'Curve Type', type: 'select', options: [
      { value: 'hypotrochoid', label: 'Hypotrochoid' },
      { value: 'rose', label: 'Rose Curve' },
    ], tooltip: 'Skeleton curve type' },
    { key: 'R', label: 'Outer Radius (R)', min: 50, max: 600, step: 1, tooltip: 'Hypotrochoid outer radius' },
    { key: 'r', label: 'Inner Radius (r)', min: 10, max: 300, step: 1, tooltip: 'Hypotrochoid inner radius' },
    { key: 'd', label: 'Pen Offset (d)', min: 10, max: 300, step: 1, tooltip: 'Hypotrochoid pen distance' },
    { key: 'roseK', label: 'Rose Petals (k)', min: 1, max: 12, step: 1, tooltip: 'Rose curve petal count' },
    { key: 'roseA', label: 'Rose Amplitude', min: 50, max: 600, step: 5, tooltip: 'Rose curve size' },
    { key: 'sampleCount', label: 'Sample Count', min: 200, max: 4000, step: 50, tooltip: 'Number of dash positions along the skeleton' },
    { key: 'harmonicK', label: 'Harmonic K', min: 1, max: 20, step: 1, tooltip: 'Frequency of the breathing envelope' },
    { key: 'innerBase', label: 'Inner Base', min: 0, max: 40, step: 1, tooltip: 'Minimum inward dash extent' },
    { key: 'innerAmp', label: 'Inner Amplitude', min: 0, max: 40, step: 1, tooltip: 'Inward extent modulation range' },
    { key: 'outerBase', label: 'Outer Base', min: 0, max: 40, step: 1, tooltip: 'Minimum outward dash extent' },
    { key: 'outerAmp', label: 'Outer Amplitude', min: 0, max: 40, step: 1, tooltip: 'Outward extent modulation range' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 2, step: 0.1, tooltip: 'Line thickness' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  turing: [
    { key: 'preset', label: 'Pattern Preset', type: 'select', options: [
      { value: 'spots', label: 'Spots' },
      { value: 'stripes', label: 'Stripes' },
      { value: 'labyrinth', label: 'Labyrinth' },
      { value: 'coral', label: 'Coral' },
    ], tooltip: 'Reaction-diffusion parameter preset' },
    { key: 'simIterations', label: 'Sim Iterations', min: 20, max: 200, step: 5, tooltip: 'Fewer = embryonic, more = fully developed' },
    { key: 'gridRes', label: 'Grid Resolution', min: 80, max: 200, step: 10, tooltip: 'Simulation grid size — higher = more detailed' },
    { key: 'targetPoints', label: 'Target Points', min: 100, max: 2000, step: 50, tooltip: 'Number of dash anchor points' },
    { key: 'minSpacing', label: 'Min Spacing', min: 3, max: 30, step: 1, tooltip: 'Minimum distance between anchor points' },
    { key: 'minDashLen', label: 'Min Dash Length', min: 2, max: 30, step: 1, tooltip: 'Shortest dashes' },
    { key: 'maxDashLen', label: 'Max Dash Length', min: 4, max: 50, step: 1, tooltip: 'Longest dashes' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 3, step: 0.1, tooltip: 'Line thickness' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  duality: [
    // Spiral + dashes
    { key: 'innerRadius', label: 'Inner Radius', min: 0, max: 200, step: 1, tooltip: 'Dead zone at center — no dashes or arcs inside this' },
    { key: 'outerRadius', label: 'Outer Radius', min: 50, max: 2000, step: 5, tooltip: 'Maximum extent of both dashes and arcs' },
    { key: 'spiralTurns', label: 'Spiral Turns', min: 1, max: 30, step: 0.5, tooltip: 'How many full rotations the dash spiral makes — controls arm spacing' },
    { key: 'spiralGrowth', label: 'Spiral Growth', min: 0.3, max: 3, step: 0.05, tooltip: '1 = linear (Archimedean), >1 = tighter center / looser edge, <1 = opposite' },
    { key: 'dashCount', label: 'Dash Count', min: 30, max: 2000, step: 10, tooltip: 'Total number of radial dashes along the spiral' },
    { key: 'dashLength', label: 'Dash Length', min: 2, max: 80, step: 1, tooltip: 'Base radial length of each dash' },
    { key: 'dashLenJitter', label: 'Dash Len Jitter', min: 0, max: 1, step: 0.05, tooltip: 'Randomizes each dash length — 0 = uniform, 1 = 0×–2× base' },
    { key: 'dashSparsity', label: 'Dash Sparsity', min: 0, max: 0.8, step: 0.05, tooltip: 'Probability of skipping a dash — creates irregular gaps' },
    { key: 'angleJitter', label: 'Angle Jitter', min: 0, max: 1, step: 0.05, tooltip: 'Angular scatter per dash — 0 = perfect spiral, 1 = noisy' },
    { key: 'dashStrokeWeight', label: 'Dash Stroke', min: 0.3, max: 4, step: 0.1, tooltip: 'Dash line thickness' },
    // Arcs
    { key: 'arcCount', label: 'Arc Count', min: 0, max: 60, step: 1, tooltip: 'Number of concentric arcs sharing the same radial range' },
    { key: 'arcSpacingNL', label: 'Arc Spacing NL', min: 0.2, max: 5, step: 0.05, tooltip: '1 = even, >1 = arcs spread outward (wavefront), <1 = cluster outward' },
    { key: 'arcRadiusJitter', label: 'Arc R Jitter', min: 0, max: 30, step: 1, tooltip: 'Random radius perturbation per arc' },
    { key: 'arcMinAngle', label: 'Arc Min Angle', min: 10, max: 180, step: 5, tooltip: 'Minimum arc span in degrees' },
    { key: 'arcMaxAngle', label: 'Arc Max Angle', min: 30, max: 358, step: 5, tooltip: 'Maximum arc span in degrees' },
    { key: 'arcMaxLength', label: 'Arc Max Length', min: 20, max: 3000, step: 10, tooltip: 'Cap arc physical length — prevents huge outer arcs' },
    { key: 'arcAngleJitter', label: 'Arc Angle Jitter', min: 0, max: 1, step: 0.01, tooltip: '0 = arcs start at 0°, 1 = fully random start angle' },
    { key: 'arcStrokeWeight', label: 'Arc Stroke', min: 0.3, max: 4, step: 0.1, tooltip: 'Arc line thickness' },
    // Interaction
    { key: 'overlapGap', label: 'Overlap Gap', min: 0, max: 40, step: 1, tooltip: 'Gap width cut at each dash/arc crossing (0 = no gaps)' },
    { key: 'overlapPriority', label: 'Overlap Priority', min: -1, max: 1, step: 0.05, tooltip: '-1 = waves dominate, 0 = equal, +1 = particles dominate' },
    { key: 'originX', label: 'Origin X', min: 0, max: 1, step: 0.01, tooltip: 'Horizontal origin (0=left, 0.5=center, 1=right)' },
    { key: 'originY', label: 'Origin Y', min: 0, max: 1, step: 0.01, tooltip: 'Vertical origin (0=top, 0.5=center, 1=bottom)' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  radialetch: [
    { key: 'lineCount', label: 'Line Count', min: 10, max: 500, step: 1, tooltip: 'Number of radial lines emanating from center' },
    { key: 'innerRadius', label: 'Inner Radius', min: 0, max: 400, step: 1, tooltip: 'Distance from center where lines begin' },
    { key: 'outerRadius', label: 'Outer Radius', min: 50, max: 2000, step: 5, tooltip: 'Distance from center where lines end' },
    { key: 'lengthJitter', label: 'Length Jitter', min: 0, max: 1, step: 0.05, tooltip: 'Randomizes inner and outer extent of each line' },
    { key: 'angleJitter', label: 'Angle Jitter', min: 0, max: 1, step: 0.05, tooltip: 'Random angular displacement per line' },
    { key: 'noiseWarp', label: 'Noise Warp', min: 0, max: 2, step: 0.05, tooltip: 'Perlin noise warps line angles for organic feel' },
    { key: 'noiseScale', label: 'Noise Scale', min: 0.001, max: 0.02, step: 0.001, tooltip: 'Frequency of warp noise — smaller = smoother' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 3, step: 0.1, tooltip: 'Line thickness' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  grid: [
    { key: 'cols', label: 'Columns', min: 2, max: 60, step: 1, tooltip: 'Number of vertical lines' },
    { key: 'rows', label: 'Rows', min: 2, max: 60, step: 1, tooltip: 'Number of horizontal lines' },
    { key: 'spacing', label: 'Spacing', min: 5, max: 100, step: 1, tooltip: 'Base distance between lines' },
    { key: 'nonLinear', label: 'Non-Linear', min: -2, max: 2, step: 0.1, tooltip: 'Curves line distribution — positive bunches toward center, negative toward edges' },
    { key: 'jitter', label: 'Jitter', min: 0, max: 30, step: 0.5, tooltip: 'Random displacement of each line position' },
    { key: 'drawHorizontal', label: 'Horizontal', min: 0, max: 1, step: 1, tooltip: '1 = draw horizontal lines, 0 = skip' },
    { key: 'drawVertical', label: 'Vertical', min: 0, max: 1, step: 1, tooltip: '1 = draw vertical lines, 0 = skip' },
    { key: 'margin', label: 'Margin', min: 0, max: 100, step: 1, tooltip: 'Extra line overshoot beyond grid bounds' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 3, step: 0.1, tooltip: 'Line thickness' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
  spiral: [
    { key: 'armCount', label: 'Arms', min: 1, max: 12, step: 1, tooltip: 'Number of spiral arms evenly spaced' },
    { key: 'turns', label: 'Turns', min: 1, max: 30, step: 0.5, tooltip: 'Number of full rotations per arm' },
    { key: 'innerRadius', label: 'Inner Radius', min: 0, max: 200, step: 1, tooltip: 'Starting radius at center' },
    { key: 'outerRadius', label: 'Outer Radius', min: 50, max: 2000, step: 5, tooltip: 'Maximum extent of spiral arms' },
    { key: 'growth', label: 'Growth', min: 0.3, max: 3, step: 0.05, tooltip: '1 = linear (Archimedean), >1 = tighter center, <1 = tighter edge' },
    { key: 'distortAmount', label: 'Distortion', min: 0, max: 80, step: 1, tooltip: 'Perlin noise displacement amount' },
    { key: 'distortScale', label: 'Distort Scale', min: 0.002, max: 0.05, step: 0.001, tooltip: 'Noise frequency — smaller = smoother warps' },
    { key: 'wobbleAmp', label: 'Wobble Amp', min: 0, max: 30, step: 0.5, tooltip: 'Sinusoidal angle wobble in degrees' },
    { key: 'wobbleFreq', label: 'Wobble Freq', min: 1, max: 40, step: 1, tooltip: 'Number of wobble oscillations per arm' },
    { key: 'stepsPerTurn', label: 'Resolution', min: 30, max: 300, step: 10, tooltip: 'Points per full rotation — higher = smoother' },
    { key: 'strokeWeight', label: 'Stroke Weight', min: 0.3, max: 3, step: 0.1, tooltip: 'Line thickness' },
    SYMMETRY_PARAM,
    START_ANGLE_PARAM,
    OFFSET_X_PARAM,
    OFFSET_Y_PARAM,
  ],
};

export const DEFAULT_COLORS = ['#00c9b1', '#ff6b6b', '#4ecdc4', '#45b7d1', '#f7dc6f', '#bb8fce'];

// Keys excluded from randomization by default (unchecked when a new layer is created).
// Users can still check them manually. Edit this list to change defaults.
export const RANDOMIZE_EXCLUDED_KEYS = [
  // Transform
  'startAngle', 'offsetX', 'offsetY', 'symmetry', 'originX', 'originY',
  // Stroke
  'strokeWeight', 'dashStrokeWeight', 'arcStrokeWeight',
  // Scale
  'patternScale',
];

// Groups collapsed by default
export const COLLAPSED_GROUPS = ['stroke', 'transform'];

// Parameter grouping — order determines display order
export const PARAM_GROUPS = [
  { id: 'structure', label: 'Structure' },
  { id: 'scale',     label: 'Scale' },
  { id: 'variation', label: 'Variation' },
  { id: 'stroke',    label: 'Stroke' },
  { id: 'transform', label: 'Transform' },
];

// Maps every param key to its group. Edit to re-group params.
export const PARAM_GROUP_MAP = {
  // Structure — skeleton, topology, counts
  R: 'structure', r: 'structure', d: 'structure', revolutions: 'structure',
  particleCount: 'structure', stepLength: 'structure',
  count: 'structure', angle: 'structure', spacing: 'structure',
  shape: 'structure', fillMode: 'structure',
  waveCount: 'structure', frequency: 'structure', amplitude: 'structure',
  lineSpacing: 'structure',
  cellCount: 'structure', drawMode: 'structure', relaxationSteps: 'structure',
  depth: 'structure', scaleFactor: 'structure',
  seedCount: 'structure', spacingC: 'structure',
  pointCount: 'structure', relaxPasses: 'structure', neighborK: 'structure',
  stepsPerParticle: 'structure', sampleEvery: 'structure',
  curveType: 'structure', roseK: 'structure', roseA: 'structure',
  sampleCount: 'structure',
  preset: 'structure', simIterations: 'structure', gridRes: 'structure',
  targetPoints: 'structure',
  spiralTurns: 'structure', dashCount: 'structure', arcCount: 'structure',
  lineCount: 'structure',
  cols: 'structure', rows: 'structure', margin: 'structure',
  drawHorizontal: 'structure', drawVertical: 'structure',
  armCount: 'structure', turns: 'structure', stepsPerTurn: 'structure',

  // Scale — size, extent, radii, lengths
  minSize: 'scale', maxSize: 'scale', sizeGrowth: 'scale',
  startScale: 'scale', scaleNonLinearity: 'scale',
  innerMax: 'scale', outerMax: 'scale',
  minDashLen: 'scale', maxDashLen: 'scale',
  innerBase: 'scale', innerAmp: 'scale', outerBase: 'scale',
  outerAmp: 'scale', harmonicK: 'scale',
  minSpacing: 'scale',
  innerRadius: 'scale', outerRadius: 'scale',
  dashLength: 'scale',
  arcMinAngle: 'scale', arcMaxAngle: 'scale', arcMaxLength: 'scale',
  arcRadiusJitter: 'scale',
  patternScale: 'scale',

  // Variation — noise, jitter, distortion
  noiseScale: 'variation', curlStrength: 'variation',
  rotation: 'variation', jitter: 'variation',
  rotationPerLevel: 'variation', strokeDepthDecay: 'variation',
  spiralGrowth: 'variation',
  dashLenJitter: 'variation', dashSparsity: 'variation',
  angleJitter: 'variation',
  arcSpacingNL: 'variation', arcAngleJitter: 'variation',
  overlapGap: 'variation', overlapPriority: 'variation',
  lengthJitter: 'variation', noiseWarp: 'variation',
  nonLinear: 'variation',
  growth: 'variation',
  distortAmount: 'variation', distortScale: 'variation',
  wobbleAmp: 'variation', wobbleFreq: 'variation',

  // Stroke — line weight, rendering
  strokeWeight: 'stroke',
  dashStrokeWeight: 'stroke', arcStrokeWeight: 'stroke',

  // Transform — position, rotation, symmetry
  symmetry: 'transform', startAngle: 'transform',
  offsetX: 'transform', offsetY: 'transform',
  originX: 'transform', originY: 'transform',
};
